

services:
  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 webhost.asgi:application
    volumes:
      - ./webhost:/app
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=http://ollama:11434
      - DJANGO_SETTINGS_MODULE=webhost.settings
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    # Uncomment the following lines if you have a GPU to pass it through
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  ollama_data: